/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sampleproject;

import com.mysql.cj.xdevapi.PreparableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author shonc
 */
public class UpdateForm extends javax.swing.JFrame {

    /**
     * Creates new form UpdateForm
     */
    public UpdateForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("ID");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Meteor Name");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Impact Date");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Impact Time");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Impact Location");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Meteor Type");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Meteor Mass");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Meteor Diameter");
        jRadioButton7.setToolTipText("");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Airburst");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton7)
                                    .addComponent(jRadioButton1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton8)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String sql="";
         if (jRadioButton1.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Name = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton2.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Impact_Date = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton3.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Impact_Time = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton4.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Impact_Location = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton5.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Type = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton6.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Mass = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton7.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Diameter_M = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton8.isSelected()) {
                sql = "UPDATE Meteor SET Airburst = ? WHERE Meteor_ID = ?";
            }
         
        try(Connection conn=DriverManager.getConnection(DatabaseController.DB_URL,DatabaseController.USER,DatabaseController.PASS);
                PreparedStatement pstmt= conn.prepareStatement(sql)
            
            ){
            if(jRadioButton6.isSelected() || jRadioButton7.isSelected())
            {
                pstmt.setDouble(1, Double.parseDouble(jTextField2.getText()));
                pstmt.setInt(2, Integer.parseInt(jTextField1.getText()));
                int rowsAffected = pstmt.executeUpdate();
            
            }
            else{
                pstmt.setString(1, jTextField2.getText());
                pstmt.setInt(2, Integer.parseInt(jTextField1.getText()));
                int rowsAffected = pstmt.executeUpdate();
            
            }
            

        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        
        }
      
        
        
        
         if (jRadioButton1.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Name = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton2.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Impact_Date = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton3.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Impact_Time = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton4.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Impact_Location = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton5.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Type = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton6.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Mass = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton7.isSelected()) {
                sql = "UPDATE Meteor SET Meteor_Diameter_M = ? WHERE Meteor_ID = ?";
            }

            if (jRadioButton8.isSelected()) {
                sql = "UPDATE Meteor SET Airburst = ? WHERE Meteor_ID = ?";
            }
                
                 
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
